# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "VCF_RANK_VARIANTS_GENMOD"
description: Rank variants using Genmod.
keywords:
  - vcf
  - variant prioritization
  - genmod
  - scoring
  - inheritance models

components:
  - genmod/annotate
  - genmod/models
  - genmod/score
  - genmod/compound
  - bcftools/view

input:
  - ch_vcf:
      description: |
        Channel with input VCF files
      structure:
        - meta:
            type: map
            description: Metadata map
        - vcf:
            type: file
            description: Input VCF file (must be uncompressed)
            pattern: "*.vcf"

  - ch_ped:
      description: |
        Channel with input PED file for genmod score and models
      structure:
        - meta:
            type: map
            description: Metadata map matching the ch_vcf channel meta
        - ped:
            type: file
            description: PED file
            pattern: "*.ped"

  - ch_genmod_reduced_penetrance:
      description: |
        (optional) reduced penetrance file for genmod models
      structure:
        - meta:
            type: map
            description: Metadata map
        - reduced_penetrance:
            type: file
            description: Reduced penetrance file
            pattern: "*.tsv"

  - ch_score_config:
      description: |
        Genmod score configuration file (rank model)
      structure:
        - meta:
            type: map
            description: Metadata map
        - score_config:
            type: file
            description: Scoring configuration file
            pattern: "*.ini"

  - val_score_only:
      description: |
        If true, only run genmod score
      type: boolean

output:
  - vcf:
      description: |
        Channel containing (compressed) VCF or BCF file
      structure:
        - meta:
            type: map
            description: Metadata map
        - vcf:
            type: file
            description: Output VCF file
            pattern: "*.{vcf,vcf.gz,bcf,bcf.gz}"

  - index:
      description: |
        Channel containing corresponding index file
      structure:
        - meta:
            type: map
            description: Metadata map
        - index:
            type: file
            description: VCF index file
            pattern: "*.{tbi,csi}"

authors:
  - "@beatrizsavinhas"
  - "@fellen31"

maintainers:
  - "@beatrizsavinhas"
  - "@fellen31"
