# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "VCF_RANK_VARIANTS_GENMOD"
description: Rank variants using Genmod.
keywords:
  - vcf
  - rank
  - variants
  - genmod
components:
  - genmod_annotate
  - genmod_models
  - genmod_score
  - genmod_compound
  - bcftools_view
input:
  - ch_vcf:
      type: file
      description: |
        The input channel containing the VCF files.
        Structure: [ val(meta), path(vcf) ]
      pattern: "*.vcf"
  - ch_ped:
      type: file
      description: |
        The input channel containing the PED files.
        Structure: [ val(meta), path(ped) ]
        Where, meta should match the meta of the VCF file in ch_vcf.
      pattern: "*.ped"
  - ch_genmod_reduced_penetrance:
      type: file
      description: |
        The input channel containing the reduced penetrance file for Genmod Models.
        Optional file.
        Structure: [ path(reduced_penetrance.tsv) ]
      pattern: "reduced_penetrance.tsv"
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - bam:
      type: file
      description: |
        Channel containing BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: file
      description: |
        Channel containing indexed BAM (BAI) files
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - csi:
      type: file
      description: |
        Channel containing CSI files
        Structure: [ val(meta), path(csi) ]
      pattern: "*.csi"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@beatrizsavinhas"
  - "@fellen31"
maintainers:
  - "@beatrizsavinhas"
  - "@fellen31"
